Updated sublime install

diff --git a/install-profiles/standard/installs/install-sublime-text b/install-profiles/standard/installs/install-sublime-text
--- a/install-profiles/standard/installs/install-sublime-text
+++ b/install-profiles/standard/installs/install-sublime-text
@@ -77,7 +77,7 @@ else
 	cp "$config_files/Package Control.sublime-settings" "$sublime_user_dir"
 fi
 
-[[ -n "$have_shellcheck" ]] && $python_bin "$ROPERDOT_DIR/bin/set-values-in-json" "$sublime_user_dir/Package Control.sublime-settings" --add-to-array installed_packages SublimeLinter-shellcheck || { echo "third set-values-in-json failed with exit code $?, continuing to debug..."; }
+# [[ -n "$have_shellcheck" ]] && $python_bin "$ROPERDOT_DIR/bin/set-values-in-json" "$sublime_user_dir/Package Control.sublime-settings" --add-to-array installed_packages SublimeLinter-shellcheck || { echo "third set-values-in-json failed with exit code $?, continuing to debug..."; }
 
 # Set terminal spawned by Terminal package to iTerm 2
 if [[ "$ROPERDOT_OS_ENV" = darwin && -d "/Applications/iTerm.app" ]]; then
